name: Run E2E Tests

on: 
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      # Configurar Java JDK 11
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Instalar dependências do projeto
      - name: Install dependencies
        run: npm ci

      # Iniciar emuladores do Firebase em segundo plano
      - name: Start Firebase Emulators
        run: |
          nohup npm run test:emulators & 
          sleep 10
      
      # Executar os testes E2E
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NODE_ENV: "test"
          JWT_SECRET: "testing"
          PROJECT_ID: "local-test-project"
          PRIVATE_KEY_ID: "test-key-id"
          PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhrdvF\nJDK\n-----END PRIVATE KEY-----\n"
          CLIENT_EMAIL: "test@test.com"
          CLIENT_ID: "test-client-id"
          AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
          TOKEN_URI: "https://oauth2.googleapis.com/token"
          AUTH_PROVIDER_X509_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
          CLIENT_X509_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509"
          UNIVERSE_DOMAIN: "googleapis.com"
